/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FilesizeRouteImport } from './routes/filesize'
import { Route as IndexRouteImport } from './routes/index'

const FilesizeRoute = FilesizeRouteImport.update({
  id: '/filesize',
  path: '/filesize',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/filesize': typeof FilesizeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/filesize': typeof FilesizeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/filesize': typeof FilesizeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/filesize'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/filesize'
  id: '__root__' | '/' | '/filesize'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FilesizeRoute: typeof FilesizeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/filesize': {
      id: '/filesize'
      path: '/filesize'
      fullPath: '/filesize'
      preLoaderRoute: typeof FilesizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FilesizeRoute: FilesizeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
